# Data Understanding

## Dataset: Melbourne House Prices Analysis


| Column | Description |
|---|---|
| `Suburb` | Name of the suburb where the property is located |
| `Address` | Street address of the property |
| `Rooms` | Number of rooms |
| `Type` | Property type: h (house, cottage, villa, terrace), u (unit, duplex), t (townhouse) |
| `Price` | Sale price in Australian dollars (AUD) |
| `Method` | Sale method: S (sold), SP (sold prior), PI (passed in), PN (sold prior, not disclosed), SN (sold, not disclosed), VB (vendor bid), W (withdrawn prior to auction), SA (sold after auction), SS (sold after auction, price not disclosed) |
| `SellerG` | Real estate agent or agency that sold the property |
| `Date` | Date the property was sold (text, format dd/mm/yyyy) |
| `Distance` | Distance from the Melbourne CBD (central business district) in km |
| `Postcode` | Postal code of the property |
| `Bedroom2` | Number of bedrooms, from a second source (it can differ from `Rooms`) |
| `Bathroom` | Number of bathrooms |
| `Car` | Number of car parking spots |
| `Landsize` | Land size in square meters |
| `BuildingArea` | Building size in square meters |
| `YearBuilt` | Year the building was built |
| `CouncilArea` | Governing council for the area |
| `Lattitude` | Latitude of the property (the column name is misspelled in the file) |
| `Longtitude` | Longitude of the property (also misspelled in the file) |
| `Regionname` | General region (West, North West, North, North East, and so on) |
| `Propertycount` | Number of properties in the suburb |

# Data Exploration

In [2]:
import numpy as np
import pandas as pd

### 1) Load Dataset

In [3]:
df = pd.read_csv('MELBOURNE_HOUSE_PRICES_LESS.csv')
df

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Postcode,Regionname,Propertycount,Distance,CouncilArea
0,Abbotsford,49 Lithgow St,3,h,1490000.0,S,Jellis,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
1,Abbotsford,59A Turner St,3,h,1220000.0,S,Marshall,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
2,Abbotsford,119B Yarra St,3,h,1420000.0,S,Nelson,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
3,Aberfeldie,68 Vida St,3,h,1515000.0,S,Barry,1/04/2017,3040,Western Metropolitan,1543,7.5,Moonee Valley City Council
4,Airport West,92 Clydesdale Rd,2,h,670000.0,S,Nelson,1/04/2017,3042,Western Metropolitan,3464,10.4,Moonee Valley City Council
...,...,...,...,...,...,...,...,...,...,...,...,...,...
63018,Roxburgh Park,3 Carr Pl,3,h,566000.0,S,Raine,31/03/2018,3064,Northern Metropolitan,5833,20.6,Hume City Council
63019,Roxburgh Park,9 Parker Ct,3,h,500000.0,S,Raine,31/03/2018,3064,Northern Metropolitan,5833,20.6,Hume City Council
63020,Roxburgh Park,5 Parkinson Wy,3,h,545000.0,S,Raine,31/03/2018,3064,Northern Metropolitan,5833,20.6,Hume City Council
63021,Thomastown,3/1 Travers St,3,u,NaN,PI,Barry,31/03/2018,3074,Northern Metropolitan,7955,15.3,Whittlesea City Council
63022,Williams Landing,1 Diadem Wy,4,h,NaN,SP,Aussie,31/03/2018,3027,Western Metropolitan,1999,17.6,Wyndham City Council

### 2)  Check Data Types

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 63023 entries, 0 to 63022
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         63023 non-null  str
 1   Address        63023 non-null  str
 2   Rooms          63023 non-null  int64
 3   Type           63023 non-null  str
 4   Price          48433 non-null  float64
 5   Method         63023 non-null  str
 6   SellerG        63023 non-null  str
 7   Date           63023 non-null  str
 8   Postcode       63023 non-null  int64
 9   Regionname     63023 non-null  str
 10  Propertycount  63023 non-null  int64
 11  Distance       63023 non-null  float64
 12  CouncilArea    63023 non-null  str
dtypes: float64(2), int64(3), str(8)
memory usage: 11.3 MB

##### Change data types

### 3)  Check Duplicates

In [5]:
df.duplicated().sum()

np.int64(2)

##### Drop Duplicates

In [7]:
df = df.drop_duplicates().reset_index(drop=True)

### 4)  Check Summary statistics for Numerical columns

In [10]:
df.describe().round(2)

          Rooms        Price  Postcode  Propertycount  Distance
count  63021.00     48432.00  63021.00       63021.00  63021.00
mean       3.11    997897.99   3125.67        7617.79     12.68
std        0.96    593505.04    125.63        4424.48      7.59
min        1.00     85000.00   3000.00          39.00      0.00
25%        3.00    620000.00   3056.00        4380.00      7.00
50%        3.00    830000.00   3107.00        6795.00     11.40
75%        4.00   1220000.00   3163.00       10412.00     16.70
max       31.00  11200000.00   3980.00       21650.00     64.10

In [12]:
df.describe(include= ['str'])

,Suburb,Address,Type,Method,SellerG,Date,Regionname,CouncilArea
count,63021,63021,63021,63021,63021,63021,63021,63021
unique,380,57754,3,9,476,112,8,34
top,Reservoir,14 Moray St,h,S,Barry,24/03/2018,Southern Metropolitan,Boroondara City Council
freq,1241,7,45052,34063,6894,1144,17559,5132