In [2]:
import pandas as pd
import plotly.express as px
import streamlit as st

In [3]:
cleaned_df = pd.read_parquet('cleaned_data.parquet')

In [40]:
df = pd.read_csv('MELBOURNE_HOUSE_PRICES_LESS.csv')

In [6]:
num_cols = cleaned_df.select_dtypes(include= 'number').columns
num_cols

Index(['Rooms', 'Price', 'Propertycount', 'Distance'], dtype='str')

In [7]:
cat_cols = cleaned_df.select_dtypes(include= 'object').columns.drop(['Postcode','Address'])
cat_cols

C:\Users\Royal\AppData\Local\Temp\ipykernel_7116\1078473836.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = cleaned_df.select_dtypes(include= 'object').columns.drop(['Postcode','Address'])

Index(['Suburb', 'Type', 'Method', 'SellerG', 'Regionname', 'CouncilArea'], dtype='str')

In [21]:
cleaned_df['Regionname'].nunique()

8

In [38]:
suburb_per_region = (
    cleaned_df.groupby(["Regionname", "Suburb"])["Propertycount"]
    .first()
    .reset_index())
suburb_per_region.index=suburb_per_region.index + 1
suburb_per_region

               Regionname           Suburb  Propertycount
1    Eastern Metropolitan        Bayswater         5030.0
2    Eastern Metropolitan  Bayswater North         3598.0
3    Eastern Metropolitan        Bellfield          790.0
4    Eastern Metropolitan        Blackburn         5713.0
5    Eastern Metropolitan  Blackburn North         2867.0
..                    ...              ...            ...
376      Western Victoria    Hopetoun Park          242.0
377      Western Victoria       Maddingley         1399.0
378      Western Victoria           Melton         3600.0
379      Western Victoria     Melton South         4718.0
380      Western Victoria   Pentland Hills           59.0

[380 rows x 3 columns]

In [37]:
region_total_properties = ( suburb_per_region.groupby("Regionname")["Propertycount"].sum().astype(int))
region_total_properties

Regionname
Eastern Metropolitan          273364
Eastern Victoria              100797
Northern Metropolitan         353606
Northern Victoria              45953
South-Eastern Metropolitan    249027
Southern Metropolitan         324889
Western Metropolitan          307870
Western Victoria               19855
Name: Propertycount, dtype: int64

In [35]:
grand_total_properties = region_total_properties.sum()
print(grand_total_properties)

1675361

In [52]:
successful_sales = cleaned_df[cleaned_df["Method"].isin(["S", "SP", "SA"])]

In [55]:
overall_avg_price = round(successful_sales["Price"].mean(),2)
print(overall_avg_price)

1017416.75

In [56]:
sold_properties = cleaned_df[~cleaned_df['Method'].isin(['PI', 'W','VB'])]
sold_properties

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Postcode,Regionname,Propertycount,Distance,CouncilArea
0,Abbotsford,49 Lithgow St,3.0,h,1490000.0,S,Jellis,2017-04-01,3067,Northern Metropolitan,4019.0,3.0,Yarra City Council
1,Abbotsford,59A Turner St,3.0,h,1220000.0,S,Marshall,2017-04-01,3067,Northern Metropolitan,4019.0,3.0,Yarra City Council
2,Abbotsford,119B Yarra St,3.0,h,1420000.0,S,Nelson,2017-04-01,3067,Northern Metropolitan,4019.0,3.0,Yarra City Council
3,Aberfeldie,68 Vida St,3.0,h,1515000.0,S,Barry,2017-04-01,3040,Western Metropolitan,1543.0,7.5,Moonee Valley City Council
4,Airport West,92 Clydesdale Rd,2.0,h,670000.0,S,Nelson,2017-04-01,3042,Western Metropolitan,3464.0,10.4,Moonee Valley City Council
...,...,...,...,...,...,...,...,...,...,...,...,...,...
63014,Preston,229 Murray Rd,3.0,h,808000.0,S,RW,2018-03-31,3072,Northern Metropolitan,14577.0,8.4,Darebin City Council
63015,Roxburgh Park,3 Carr Pl,3.0,h,566000.0,S,Raine,2018-03-31,3064,Northern Metropolitan,5833.0,20.6,Hume City Council
63016,Roxburgh Park,9 Parker Ct,3.0,h,500000.0,S,Raine,2018-03-31,3064,Northern Metropolitan,5833.0,20.6,Hume City Council
63017,Roxburgh Park,5 Parkinson Wy,3.0,h,545000.0,S,Raine,2018-03-31,3064,Northern Metropolitan,5833.0,20.6,Hume City Council
63019,Williams Landing,1 Diadem Wy,4.0,h,659100.0,SP,Aussie,2018-03-31,3027,Western Metropolitan,1999.0,17.6,Wyndham City Council

In [60]:
total_revenue = sold_properties["Price"].sum().astype(int)
print(total_revenue)

47688199198

In [8]:
Regions_list=['All Regions'] + cleaned_df['Regionname'].unique().tolist()
Regions_list

['All Regions',
 'Northern Metropolitan',
 'Western Metropolitan',
 'Southern Metropolitan',
 'South-Eastern Metropolitan',
 'Eastern Metropolitan',
 'Northern Victoria',
 'Western Victoria',
 'Eastern Victoria']